[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.22"
pretty_env_logger="0.5.0"
anyhow="1.0.90"
eframe="0.29.1"
rfd="*"
futures = "0.3.31"
systemicons="*"
egui_extras = {version="*", features = ["default", "all_loaders"]}
