[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
ffmpeg-next = {path="../rust-ffmpeg-master", features=["codec", "format"]}
log = "*"
pretty_env_logger="*"
anyhow="*"
eframe="*"